import { useState } from "react"
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"
import { AdminSidebar } from "./sidebar"
import { Separator } from "@/components/ui/separator"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { ScrollArea } from "@/components/ui/scroll-area"
import { AlertTriangle, CheckCircle2, Trash2 } from "lucide-react"

const skillReports = [
  {
    id: 1,
    user: "Jane Smith",
    skill: "Hacking Basics",
    description: "This user wrote offensive or unrelated content.",
    submittedAt: "2025-07-12 11:43",
  },
  {
    id: 2,
    user: "Mark Evans",
    skill: "Cooking in Java",
    description: "Spam text used in skill name, looks autogenerated.",
    submittedAt: "2025-07-11 16:10",
  },
  {
    id: 3,
    user: "Lily Zhang",
    skill: "🔥 Free Money Tricks",
    description: "Clearly misleading skill post. Not allowed.",
    submittedAt: "2025-07-10 08:57",
  },
]

export default function Skillmoderation() {
  const [reports, setReports] = useState(skillReports)

  const handleApprove = (id: number) => {
    setReports((prev) => prev.filter((r) => r.id !== id))
    alert(`Approved skill report #${id}`)
  }

  const handleReject = (id: number) => {
    setReports((prev) => prev.filter((r) => r.id !== id))
    alert(`Rejected and removed skill report #${id}`)
  }

  return (
    <SidebarProvider
      style={{ "--sidebar-width": "19rem" } as React.CSSProperties}
    >
      <AdminSidebar />
      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center gap-4 px-6 bg-background/60 backdrop-blur-md border-b sticky top-0 z-10">
          <SidebarTrigger className="-ml-1" />
          <h1 className="text-2xl font-bold tracking-tight">Skill Moderation</h1>
        </header>

        <div className="p-6 space-y-6">
          <div className="bg-background border shadow-sm rounded-xl">
            <div className="px-6 py-4 border-b flex items-center justify-between">
              <div className="flex items-center gap-3">
                <AlertTriangle className="w-6 h-6 text-yellow-500" />
                <h2 className="text-xl font-semibold">Reported Skills</h2>
              </div>
              <Badge variant="destructive" className="text-xs px-2 py-1 rounded-full">
                {reports.length} Pending
              </Badge>
            </div>

            <ScrollArea className="max-h-[65vh] divide-y divide-border">
              {reports.length === 0 ? (
                <div className="text-center text-sm text-muted-foreground py-6">
                  ✅ No reported skills currently.
                </div>
              ) : (
                reports.map((report) => (
                  <div
                    key={report.id}
                    className="grid md:grid-cols-3 items-center px-6 py-5 gap-4 hover:bg-muted transition rounded-md"
                  >
                    <div className="col-span-2">
                      <h3 className="text-base font-medium text-foreground">
                        {report.skill} <span className="text-xs text-muted-foreground">(#{report.id})</span>
                      </h3>
                      <p className="text-sm text-muted-foreground">
                        Reported by <strong>{report.user}</strong> on{" "}
                        <span className="font-medium">{report.submittedAt}</span>
                      </p>
                      <p className="mt-1 text-sm text-foreground">
                        <span className="font-medium">Reason:</span> {report.description}
                      </p>
                    </div>
                    <div className="flex flex-col md:flex-row md:justify-end gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleApprove(report.id)}
                      >
                        <CheckCircle2 className="w-4 h-4 mr-1" /> Approve
                      </Button>
                      <Button
                        variant="destructive"
                        size="sm"
                        onClick={() => handleReject(report.id)}
                      >
                        <Trash2 className="w-4 h-4 mr-1" /> Reject
                      </Button>
                    </div>
                  </div>
                ))
              )}
            </ScrollArea>
          </div>
        </div>
      </SidebarInset>
    </SidebarProvider>
  )
}
